---
title: "Règlement"
---
<br> 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<br>


## Section 1 : Introduction

Le but du jeu est de pronostiquer le score de chaque match de la Coupe du Monde 2018 :

- 48 matchs de poules, du jeudi 14 juin au jeudi 28 juin ;

- 16 matchs à élimination directe (huitièmes de finale, quarts de finale, demi-finales, match pour la 3e place, finale), du samedi 30 juin au dimanche 15 juillet.

Pour qu’un pronostic soit valable, celui-ci doit avoir été sauvegardé avant le coup d’envoi du match concerné (les dates et horaires des matchs sont inscrits dans le fichier Excel).

De plus, lors de son inscription, chaque participant pronostique le nom du pays qui selon lui remportera la compétition (**voir section 4**).

<br>

***

<br>

## Section 2 : Principe du jeu

Le nombre de points que rapporte un pronostic dépend :

- Du niveau de la compétition auquel appartient le match : match de poule, huitièmes de finale, quart de finale, etc.

- De l'exactitude du pronostic : bon vainqueur, bon vainqueur et bonne différence de buts, bon vainqueur et score exact.

<br>

***

<br>

## Section 3 : Attribution des points

Les points seront attribués de la manière suivante :

| **Tour** 	| **Bon vainqueur** 	| **Bon vainqueur avec bonne différence de buts** 	| **Bon vainqueur avec score exact** 	|
|---------------------	|---------------	|---------------------------------------------	|--------------------------------	|
| Matchs de poule 	| 2 	| 4 	| 7 	|
| Huitièmes de finale 	| 4 	| 6 	| 9 	|
| Quarts de finale 	| 6 	| 8 	| 11 	|
| Demi-finales 	| 8 	| 10 	| 13 	|
| Troisième place 	| 10 	| 12 	| 15 	|
| Finale 	| 12 	| 14 	| 17 	|

A partir des huitièmes de finale :

-	en cas de prolongations, le score qui sera pris en compte sera le score à l’issue des prolongations.

- lorsqu’un participant pronostique un match nul, il doit indiquer le nom du pays vainqueur de la séance de tirs au but. Il ne pourra obtenir de points que s’il choisit le bon pays vainqueur. 

<br>
<br>

### Exemple 1 - Match de poule : Maroc 2-0 Iran
| **Pronostic** 	| **Points attribués** 	| **Explications** 	|
|---------------------------------------------------------------------------------	|------------------	|---------------------------------------------	|
| 0-2 pour l’Iran 	| 0 pt 	| mauvais résultat 	|
| 0-0 	| 0 pt 	| mauvais résultat 	|
| 1-0 pour le Maroc 	| 2 pts 	| bon vainqueur 	|
| 3-1 pour le Maroc 	| 4 pts 	| bon vainqueur avec bonne différence de buts 	|
| 2-0 pour le Maroc 	| 7 pts 	| bon vainqueur avec score exact 	|

<br>

### Exemple 2 - Match de poule : Colombie 1-1 Japon
| **Pronostic** 	| **Points attribués** 	| **Explications** 	|
|---------------------------------------------------------------------------------	|------------------	|---------------------------------------------	|
| 1-0 pour la Colombie 	| 0 pt 	| mauvais résultat 	|
| 0-2 pour le Japon 	| 0 pt 	| mauvais résultat 	|
| 0-0 	| 4 pts 	| bon vainqueur avec bonne différence de buts 	|
| 1-1 	| 7 pts 	| bon vainqueur avec score exact 	|

<br>

### Exemple 3 - Huitième de finale : France 2-1 Croatie
| **Pronostic** 	| **Points attribués** 	| **Explications** 	|
|---------------------------------------------------------------------------------	|------------------	|---------------------------------------------	|
| 0-1 pour la Croatie 	| 0 pt 	| mauvais résultat 	|
| 2-2, victoire de la Croatie aux tirs au but 	| 0 pt 	| mauvais résultat 	|
| 0-0, victoire de la France aux tirs au but 	| 4 pts 	| bon vainqueur 	|
| 2-0 pour la France 	| 4 pts 	| bon vainqueur 	|
| 1-0 pour la France 	| 6 pts 	| bon vainqueur avec bonne différence de buts 	|
| 2-1 pour la France 	| 9 pts 	| bon vainqueur avec score exact 	|

<br>

### Exemple 4 - Quart de finale : Mexique 1-1 Belgique, victoire de la Belgique aux tirs au but
| **Pronostic** 	| **Points attribués** 	| **Explications** 	|
|---------------------------------------------------------------------------------	|------------------	|---------------------------------------------	|
| 1-0 pour le Mexique 	| 0 pt 	| mauvais résultat 	|
| 0-0, victoire du Mexique aux tirs au but 	| 0 pt 	| mauvais résultat 	|
| 1-1, victoire du Mexique aux tirs au but 	| 0 pt 	| mauvais résultat 	|
| 0-2 pour la Belgique 	| 6 pts 	| bon vainqueur 	|
| 0-0, victoire de la Belgique aux tirs au but 	| 8 pts 	| bon vainqueur avec bonne différence de buts 	|
| 1-1, victoire de la Belgique aux tirs au but 	| 11 pts 	| bon résultat avec score exact 	|

<br>


<br>

## Section 4 : Bonus vainqueur

Lors de son inscription, chaque participant pronostique le nom du pays qui remportera la compétition selon lui.  

Un bonus de points sera attribué aux participants ayant trouvé le bon vainqueur de la Coupe du Monde 2018. Ce bonus sera équivalent à la cote attribuée au pays champion du monde par le site « Parions Sport » avant le début du mondial :

| Champion 	| Bonus 	| Champion 	| Bonus 	| Champion 	| Bonus 	| Champion 	| Bonus 	|
|------------	|-------	|----------	|-------	|-----------	|-------	|-----------------	|-------	|
| Allemagne 	| 5 	| Uruguay 	| 28 	| Suède 	| 100 	| Costa Rica 	| 300 	|
| Brésil 	| 5 	| Colombie 	| 30 	| Sénégal 	| 150 	| Japon 	| 300 	|
| Espagne 	| 6 	| Croatie 	| 30 	| Serbie 	| 150 	| Maroc 	| 300 	|
| France 	| 6,5 	| Russie 	| 35 	| Egypte 	| 175 	| Corée du Sud 	| 500 	|
| Argentine 	| 9 	| Pologne 	| 45 	| Islande 	| 200 	| Iran 	| 500 	|
| Belgique 	| 11 	| Danemark 	| 80 	| Nigeria 	| 200 	| Tunisie 	| 500 	|
| Angleterre 	| 16 	| Suisse 	| 80 	| Pérou 	| 200 	| Arabie Saoudite 	| 900 	|
| Portugal 	| 22 	| Mexique 	| 90 	| Australie 	| 300 	| Panama 	| 900 	|